project:
  type: website
  resources:
    - data
    - img
    - outputs/**
  output-dir: docs

website:
  title: "Overdosed"
  favicon: "img/favicon-32x32.png"
  navbar:
    search: true
    left:
      - href: about.qmd
        text: About
      - href: index.html
        text: Dashboard
      - href: findings.html
        text: Findings
      - href: references.html
        text: References  
    right:
      - text: "Back to Portfolio"
        href: "https://courtneyrgreen.com/"
      - icon: github
        href: "https://github.com/courtneyrgreen/us-overdose-crisis.git"

  
format:
  html:
      theme: 
        - morph
        - styles.scss
      toc: true
      toc-location: right
      toc-depth: 4

#editor: visual